### ISSUE TITLE
keybind для открытия caк

### ISSUE THREAD

**Issue by GoodNlCE** [TeoDar/stalcraft_signals#13]
У меня переназначена клавиша устройства, нужно сделать кастомную копку в конфигурации для смены активации устройства

**Comment by TeoDar** [comment]
Я вас не понял. Опишите поподробнее.
Также прошу учесть, что global hotkey реализованы через библиотеку ahk, которая поддерживает не все устройства ввода.

**Comment by GoodNlCE** [comment]
САК открывается на клавишу X, у меня переназначено на правый shift, соответственно прога пытается открыть САК, но ничего не происходит

**Comment by GoodNlCE** [comment]
Прошу добавить доп настройку в программе, которая позволит указать на какую клавишу в игре открывается САК

**Comment by TeoDar** [comment]
Понял. Постараюсь сегодня новый релиз с этой настройкой сделать👍

**Comment by TeoDar** [comment]
Добавлено в версии 1.3
