### ISSUE TITLE
Не работает авто запуск поиска сигнала

### ISSUE THREAD

**Issue by Anatoliy0299** [TeoDar/stalcraft_signals#2]
Привет, когда я запускаю программу, она начинает работать, но когда появляется сигнал,  она начинает писать в смд что сигнал найден, а  потом просто начинает заново нажимать x. У меня виндовс 11, может в этом проблема

**Comment by TeoDar** [comment]
Привет. Приложи скрин cmd. 
AHK точно по пути в инструкции установлен? Игра в оконном режиме на весь экран? Какое разрешение экрана?

**Comment by Anatoliy0299** [comment]
![Gs2ZxOiKwp](https://github.com/TeoDar/stalcraft_signals/assets/150075674/6602b5a4-b598-4677-9a3f-1ef46c6412fc) ахк качал по инструкции, игра в оконном режиме, разрешение экрана 1920 1080, один раз смог даже нажать на кнопку пуск, но сразу нажал x и заново начал работу, наверное даже приложу видео

**Comment by TeoDar** [comment]
Хмм. Попробуйте оконный режим с рамкой.

**Comment by Anatoliy0299** [comment]
https://disk.yandex.ru/i/00dyuIm9I3NCMw
ссылка на видео

**Comment by TeoDar** [comment]
Чёт видео обрезанное. Можешь записать от момента запуска exeшника до неправильной работы?

**Comment by TeoDar** [comment]
Возможно я знаю в чём была проблема. Попробуй [сборку 0.2](https://github.com/TeoDar/stalcraft_signals/releases/tag/0.2)

**Comment by Anatoliy0299** [comment]
спасибо мужик, заработало👍. Идея: добавить либо дискорд вебхук чтобы уведомляло когда прога нашла сигнал, либо в телеграмм бота

**Comment by Anatoliy0299** [comment]
а в полноэкранном режиме ты не тестил, запускать можно или не?

**Comment by TeoDar** [comment]
Рад что помог) Про телегу думал. Да надо бы и интерфейсик простой накидать, чтобы поверх экрана был. Да лень))) Может чуть позже с телегой попробую сделать. Лично я колонки погромче делал и уходил делать дела.

Полноэкранный режим не подойдёт. Там АХК вроде баговал и коэффициенты координат кнопок другие.
