### ISSUE TITLE
Помощь в настройке..

### ISSUE THREAD

**Issue by Humawayy** [TeoDar/stalcraft_signals#3]
Здравствуйте, можно ли подробное видео как настроить данную програмку? либо ошибка либо он просто бексонечно открывает и закрывает САК1 и ничего не могу с этим поделать.

**Comment by SannoV** [comment]
Ну как я понял , ты просто ложишься где-то , запускаешь прогу и жмешь F3. Скрипт открывает и закрывает сак , при этом проверяет изменение цвета состояния сигнала. Как только сигнал появляется , скрипт тыкает средний рендж и нажимает поиск , а на 6 лампочке выключает. Крч тебе просто ничего не надо трогать пока оно ищет и не сворачивать игру. Ну сам сигнал тебе вручную только забирать с детектором надо. 
Только , к слову , у меня иногда багует поиск , или без сигнала нажимается поиск или , когда кто-то опередил (вероятно тоже с макросами) , загораются все красные лампочки и этот скрипт путается чет , приходится его вручную перезапускать + перезаход на перса , чтобы сбросить зависшие лампочки.
