### ISSUE TITLE
Макрос пофиксили?

### ISSUE THREAD

**Issue by Pley228** [TeoDar/stalcraft_signals#4]
Добрый день ,такая проблема.Сак просто окрывается и закрывается ,но на сигналы не как не реагирует.Как это можно исправить?

**Comment by TeoDar** [comment]
Добрый день. Перед запуском, выполнили всё, что прописано в инструкции?

**Comment by Pley228** [comment]
> Добрый день. Перед запуском, выполнили всё, что прописано в инструкции?

Да,все выполнил ,но не хочет работать
