### ISSUE TITLE
Проблема со скриптом

### ISSUE THREAD

**Issue by yungprunce** [TeoDar/stalcraft_signals#5]
После того как загорается лампочка ничего не происходит, просто продолжает включать выключать дшд. Возможно причина в том, что у меня монитор 21x9 и разрешение экрана 2560x1080. Хотел бы попросить помощи в исправлении этого

**Comment by TeoDar** [comment]
Скоро перепишу на возможность переконфигурирования под свои мониторы и вы сможете настроить под себя.
