### ISSUE TITLE
Задержка между кликами

### ISSUE THREAD

**Issue by GeniyN** [TeoDar/stalcraft_signals#8]
У меня скрипт при нахождении сигнала, может не успеть нажать на кнопку Средняя, или вообще нажать на тумблер
Хотелось бы видеть возможность установки задержки для этих действий, хоть в пару мс

**Comment by TeoDar** [comment]
Сделаем👍

**Comment by GeniyN** [comment]
Также еще после нажатия на кнопку "Поиск" в саке, он может сбросить, нажав на тумблер еще раз

**Comment by TeoDar** [comment]
Добавлено в новом релизе
